// English version of the quiz, in exactly the same order as QUIZ in data-quiz.js.
// Each entry: [topic, question, correct answer, [3 wrong answers], explanation]
window.QUIZ_EN = [
// ——— 1 ———
[1,'How many states are members of the United Nations?','193',['185','195','201'],'193 member states; the Holy See (Vatican) and Palestine have observer status.'],
[1,'Which states have observer status at the UN?','The Vatican and Palestine',['Switzerland and the Vatican','Taiwan and Kosovo','Palestine and Western Sahara'],'Switzerland joined the UN in 2002; Taiwan and Kosovo are neither members nor observers.'],
[1,'Which period in the formation of the political map began after World War I?','The Contemporary period',['The Modern period','The Medieval period','The Ancient period'],'Periods: Ancient (to the 5th c.), Medieval (5th–15th c.), Modern (15th–16th c. to the end of WWI), Contemporary (after WWI).'],
[1,'Which period does the Age of Discovery belong to?','The Modern period',['The Medieval period','The Contemporary period','The Ancient period'],'The Modern period begins at the turn of the 15th–16th centuries with the great geographical discoveries and colonial conquests.'],
[1,'What was the largest change to the political map after World War II?','The collapse of the colonial system',['The breakup of the USSR','German reunification','The creation of the EU'],'Decolonization produced more than 100 new independent states in Asia, Africa, Latin America and Oceania.'],
[1,'Which year is known as the “Year of Africa” (17 countries became independent)?','1960',['1945','1957','1975'],'In 1960, 17 African colonies became independent.'],
[1,'In which year were West and East Germany reunified?','1990',['1989','1991','1993'],'The Berlin Wall fell in 1989; Germany reunified on 3 October 1990.'],
[1,'Which is the newest UN member state?','South Sudan',['Timor-Leste','Montenegro','Eritrea'],'South Sudan separated from Sudan and joined the UN in 2011.'],
[1,'Which state emerged peacefully in 1993 from the “Velvet Divorce”?','Slovakia (and Czechia)',['Eritrea','Croatia','Montenegro'],'Czechoslovakia peacefully split into Czechia and Slovakia on 1 January 1993.'],
[1,'From which state did Eritrea separate in 1993?','Ethiopia',['Sudan','Somalia','Djibouti'],'Eritrea became independent from Ethiopia after a 1993 referendum.'],
[1,'Which of these is a qualitative change to the political map?','A change in the form of government (e.g. monarchy → republic)',['The reunification of West and East Germany','The breakup of the USSR','The annexation of territory after a war'],'Quantitative changes alter territory or the number of states; qualitative changes alter the historical formation, form of government, or sovereignty.'],
[1,'Which state became a republic in 2021, removing the British monarch as head of state?','Barbados',['Jamaica','Australia','Mauritius'],'Barbados has been a republic since 30 November 2021 and remains in the Commonwealth.'],
[1,'In which year was Hong Kong handed over to China?','1997',['1984','1999','2001'],'The UK returned Hong Kong to China in 1997; Portugal returned Macao in 1999.'],
[1,'Which state became independent from Indonesia in 2002?','Timor-Leste',['Brunei','Papua New Guinea','Singapore'],'Timor-Leste (East Timor), a former Portuguese colony, was occupied by Indonesia from 1975 to 1999.'],
// ——— 2 ———
[2,'How wide are territorial waters under the 1982 UN Convention on the Law of the Sea?','12 nautical miles',['3 nautical miles','24 nautical miles','200 nautical miles'],'The territorial sea extends up to 12 miles from the baselines; the state has full sovereignty over it.'],
[2,'How wide is the exclusive economic zone (EEZ)?','200 nautical miles',['12 nautical miles','24 nautical miles','350 nautical miles'],'In the EEZ the state has sovereign rights to explore and exploit resources, but navigation is free.'],
[2,'How wide is the contiguous zone (from the baselines)?','24 nautical miles',['12 nautical miles','50 nautical miles','200 nautical miles'],'In the contiguous zone the state exercises customs, sanitary and immigration control.'],
[2,'How long is one nautical mile?','1,852 m',['1,609 m','1,000 m','2,000 m'],'A nautical mile is about one minute of arc along a meridian. 1,609 m is the statute (land) mile.'],
[2,'What is the maximum distance a state’s continental shelf can extend (if confirmed by the UN Commission)?','350 nautical miles',['200 nautical miles','24 nautical miles','500 nautical miles'],'The shelf is at least 200 miles; where the continent extends geologically, up to 350 miles or 100 miles beyond the 2,500 m isobath.'],
[2,'The US–Canada border along the 49th parallel is an example of which type of border?','Geometric (astronomical)',['Orographic','Hydrographic','Ethnographic'],'Geometric borders follow straight lines, parallels and meridians; they are typical of Africa and North America.'],
[2,'A border that runs along a mountain ridge is called…','Orographic',['Hydrographic','Geometric','Maritime'],'Orographic borders follow relief (the Pyrenees, the Andes); hydrographic borders follow rivers and lakes.'],
[2,'What is border delimitation?','Defining the border by treaty and drawing it on a map',['Marking the border on the ground with border posts','Inspecting and restoring border markers','Unilaterally giving up part of a territory'],'Delimitation happens on the map, demarcation on the ground.'],
[2,'Which state is an enclave entirely surrounded by South Africa?','Lesotho',['Eswatini','Botswana','Namibia'],'Enclaves: Lesotho (in South Africa), San Marino and the Vatican (in Italy).'],
[2,'Relative to the rest of Russia, the Kaliningrad Oblast is…','An exclave',['An enclave','A condominium','A protectorate'],'An exclave is part of a state separated from its main territory by other states.'],
[2,'Which state is the largest by area after Russia?','Canada',['China','United States','Brazil'],'The seven largest by area: Russia, Canada, China/USA, Brazil, Australia, India.'],
[2,'Which country is NOT among the seven largest by area?','Argentina',['Australia','India','Brazil'],'Argentina is 8th by area; India is 7th.'],
[2,'Which international treaty “froze” territorial claims to Antarctica?','The Antarctic Treaty of 1959',['The UN Convention on the Law of the Sea (1982)','The Treaty of Versailles (1919)','The Helsinki Final Act (1975)'],'Antarctica may be used for peaceful purposes only; national claims are frozen.'],
[2,'Which is the smallest state in the world by area?','Vatican City',['Monaco','Nauru','San Marino'],'The Vatican covers about 0.44 km²; Monaco about 2 km².'],
// ——— 3 ———
[3,'Roughly how many monarchies are there in the world today?','About 40 (43)',['About 10','About 25','About 70'],'43 monarchies, 15 of which are Commonwealth realms headed by the British monarch.'],
[3,'Which state is an absolute monarchy?','Oman',['United Kingdom','Spain','Japan'],'Absolute monarchies: Saudi Arabia, Oman, Qatar, the UAE, Brunei, Eswatini.'],
[3,'Which state is a theocratic monarchy?','Vatican City',['Iran','Nepal','Bhutan'],'The head of the Vatican is the Pope. Iran is an Islamic republic; Nepal has been a republic since 2008.'],
[3,'Which of these states is a republic?','France',['Netherlands','Belgium','Sweden'],'The Netherlands, Belgium and Sweden are constitutional monarchies.'],
[3,'In which country is the British monarch head of state?','Canada',['India','South Africa','Ireland'],'Commonwealth realms: Canada, Australia, New Zealand, Jamaica, the Bahamas and others (15 including the UK).'],
[3,'Which republic is parliamentary?','Germany',['United States','Brazil','Mexico'],'In a parliamentary republic the government is formed by parliament; the president has mostly ceremonial functions.'],
[3,'Which republic is presidential?','United States',['Germany','Italy','India'],'In a presidential republic the president is both head of state and head of government.'],
[3,'Which state is a federation?','Brazil',['France','Poland','Japan'],'Federations include Russia, the USA, Canada, Mexico, Brazil, Germany, India, Australia, Nigeria and others (about 25).'],
[3,'What are the constituent units of the German federation called?','Länder (federal states)',['States','Cantons','Provinces'],'Länder — Germany and Austria; cantons — Switzerland; provinces — Canada, Argentina; states — USA, India, Brazil.'],
[3,'What are the constituent units of Switzerland called?','Cantons',['Länder','Departments','Voivodeships'],'Switzerland consists of 26 cantons.'],
[3,'Where is OPEC headquartered?','Vienna',['Riyadh','Baghdad','Geneva'],'OPEC was founded in Baghdad in 1960; its headquarters has been in Vienna since 1965.'],
[3,'Where is NATO headquartered?','Brussels',['Washington, D.C.','London','Geneva'],'NATO headquarters is in Brussels, Belgium.'],
[3,'Where is the African Union headquartered?','Addis Ababa',['Cairo','Nairobi','Abuja'],'Addis Ababa, Ethiopia.'],
[3,'Where is the Arab League headquartered?','Cairo',['Riyadh','Damascus','Baghdad'],'The Arab League was founded in 1945; its headquarters is in Cairo.'],
[3,'Where is the ASEAN Secretariat?','Jakarta',['Singapore','Bangkok','Manila'],'ASEAN was founded in 1967; its secretariat is in Jakarta.'],
[3,'Which of these organizations is a military-political alliance?','CSTO',['OPEC','ASEAN','MERCOSUR'],'Military-political blocs: NATO, CSTO. OPEC is sectoral; ASEAN and MERCOSUR are regional economic groupings.'],
[3,'Which organization is sectoral (industry-based)?','OPEC',['EU','CIS','UN'],'OPEC unites oil-exporting countries.'],
[3,'Which country belongs to both the EU and NATO?','Poland',['Switzerland','Norway','Austria'],'Norway is in NATO but not the EU; Austria is in the EU but not NATO; Switzerland is in neither.'],
[3,'Which country joined NATO in 2024?','Sweden',['Finland','Austria','Ireland'],'Finland joined in 2023, Sweden in March 2024.'],
[3,'Which country joined BRICS in January 2025?','Indonesia',['Turkey','Argentina','Saudi Arabia'],'Argentina declined to join; Indonesia became the 10th member.'],
[3,'Which country became a full SCO member in 2024?','Belarus',['Iran','Turkey','Mongolia'],'Iran joined the SCO in 2023, Belarus in 2024.'],
[3,'Which of these countries is an OPEC member?','Venezuela',['Russia','Mexico','Norway'],'Russia and Mexico take part in OPEC+ but are not OPEC members.'],
[3,'Which country left OPEC in 2024?','Angola',['Nigeria','Gabon','Algeria'],'Angola left OPEC on 1 January 2024.'],
[3,'Which country is NOT a member of the Gulf Cooperation Council?','Iran',['Qatar','Oman','Bahrain'],'GCC: Saudi Arabia, the UAE, Kuwait, Qatar, Bahrain, Oman.'],
[3,'Which country is NOT a member of the EAEU?','Tajikistan',['Armenia','Kyrgyzstan','Kazakhstan'],'EAEU: Russia, Belarus, Kazakhstan, Armenia, Kyrgyzstan.'],
[3,'Which country became ASEAN’s 11th member in 2025?','Timor-Leste',['Papua New Guinea','Sri Lanka','Bangladesh'],'Timor-Leste was admitted to ASEAN in October 2025.'],
[3,'Which country became a full MERCOSUR member in 2024?','Bolivia',['Chile','Venezuela','Peru'],'MERCOSUR members: Argentina, Brazil, Paraguay, Uruguay, Bolivia; Venezuela is suspended.'],
[3,'Where is the CIS Executive Committee located?','Minsk',['Moscow','Astana','Bishkek'],'The CIS Executive Committee is in Minsk.'],
// ——— 4 ———
[4,'What is resource endowment (resource availability)?','The ratio between the amount of natural resources and the rate at which they are used',['The total volume of resource reserves in a country','A country’s share of world output','The value of raw-material exports'],'It is expressed as the number of years a resource will last, or as reserves per capita.'],
[4,'Natural conditions are…','Natural bodies and forces that matter for human life but are not directly used in production',['All natural components used as raw materials','Mineral deposits only','Resources created by people'],'For example, climate and relief. Natural resources, by contrast, are used directly in production.'],
[4,'Which of these are exhaustible but renewable resources?','Forest resources',['Oil','Coal','Solar energy'],'Renewable: biological, land, water. Non-renewable: mineral. Inexhaustible: solar, wind and geothermal energy.'],
[4,'Which resources are exhaustible and non-renewable?','Mineral resources',['Forest resources','Wind energy','Fish stocks'],'Mineral deposits are not restored on a historical time scale.'],
[4,'Which resource is inexhaustible?','Wind energy',['Natural gas','Soils','Fresh water in lakes'],'Inexhaustible: the energy of the Sun, wind, tides and the Earth’s internal heat.'],
[4,'Which mineral fuel has the largest resource endowment in the world?','Coal',['Oil','Natural gas','Uranium ore'],'Coal will last more than 100 years; oil and gas about 50 years at current output.'],
[4,'Roughly how many years will proven oil reserves last at current output?','About 50 years',['About 10 years','About 150 years','About 500 years'],'World oil resource endowment is roughly 50 years.'],
[4,'What is the classification of resources into exhaustible and inexhaustible called?','Ecological (by exhaustibility)',['Natural (by origin)','Economic (by use)','Territorial'],'The natural classification gives mineral, land, water, etc.; the economic one gives resources for industry, agriculture, and so on.'],
// ——— 5 ———
[5,'Which country has the largest proven oil reserves?','Venezuela',['Saudi Arabia','Russia','United States'],'Venezuela (the Orinoco Belt) holds about 17% of world reserves, followed by Saudi Arabia, Iran and Canada.'],
[5,'Which country has the largest natural gas reserves?','Russia',['Qatar','Iran','United States'],'Leaders in gas reserves: Russia, Iran, Qatar.'],
[5,'Which country is the world’s largest oil producer?','United States',['Saudi Arabia','Russia','China'],'Since 2018 the USA has led oil production thanks to shale output.'],
[5,'Which country mines the most coal?','China',['United States','India','Australia'],'China accounts for more than half of world coal output.'],
[5,'Which is the world’s largest oil and gas basin?','The Persian Gulf basin',['The West Siberian basin','The Gulf of Mexico basin','The North Sea basin'],'The Persian Gulf basin holds about half of the world’s oil reserves.'],
[5,'In which country is the Ruhr coal basin?','Germany',['France','Poland','Belgium'],'The Ruhr is Germany’s largest coal basin and an old industrial region.'],
[5,'The Upper Silesian coal basin lies mainly in…','Poland',['Germany','Hungary','Romania'],'Upper Silesia is Poland’s main coal region (partly in Czechia).'],
[5,'The Appalachian coal basin is in…','the United States',['Canada','Australia','the United Kingdom'],'The Appalachian basin is the largest coal basin in the USA.'],
[5,'The Maracaibo oil and gas basin is in…','Venezuela',['Mexico','Colombia','Brazil'],'Lake Maracaibo is Venezuela’s oldest oil region.'],
[5,'Which countries produce oil and gas in the North Sea?','Norway and the United Kingdom',['Germany and France','Sweden and Finland','Denmark and Poland'],'The North Sea basin is divided mainly between Norway and the UK.'],
[5,'Africa’s “Copperbelt” lies in…','Zambia and DR Congo',['South Africa and Namibia','Ghana and Nigeria','Kenya and Tanzania'],'The Copperbelt is a copper and cobalt mining zone on the Zambia–DR Congo border.'],
[5,'Which country has the largest copper reserves and output?','Chile',['Peru','United States','China'],'Chile (Chuquicamata, Escondida mines) is the world leader in copper.'],
[5,'Which country has the largest bauxite reserves?','Guinea',['Australia','Jamaica','Brazil'],'Guinea has the largest reserves; Australia and Guinea lead production.'],
[5,'Which country leads the world in iron ore mining?','Australia',['Brazil','China','India'],'Australia (the Pilbara region) is first, Brazil second.'],
[5,'Which country is the world leader in uranium mining?','Kazakhstan',['Canada','Australia','Niger'],'Kazakhstan supplies about 40% of the world’s uranium.'],
[5,'Which countries form the “lithium triangle”?','Chile, Argentina, Bolivia',['Australia, China, Chile','Peru, Ecuador, Colombia','Brazil, Paraguay, Uruguay'],'Most of the world’s lithium reserves are in the salt flats of the Andes.'],
[5,'Which country is the largest producer of platinum-group metals?','South Africa',['Russia','Canada','Zimbabwe'],'South Africa (Bushveld Complex) produces about 70% of the world’s platinum.'],
[5,'The West Siberian basin is mainly…','An oil and gas basin in Russia',['A coal basin in Russia','An iron ore basin in Kazakhstan','An oil and gas basin in Canada'],'Western Siberia is Russia’s main oil and gas producing region.'],
// ——— 6 ———
[6,'Roughly what share of the world’s land is arable?','About 11%',['About 3%','About 30%','About 50%'],'Structure: arable land ~11%, meadows and pastures ~25%, forests ~30%, the rest low-productive and built-up land.'],
[6,'Which country has the largest freshwater (river runoff) resources?','Brazil',['Russia','Canada','United States'],'Brazil (the Amazon) is first, Russia second.'],
[6,'Which sector is the world’s largest consumer of fresh water?','Agriculture (irrigation)',['Industry','Municipal use','Energy'],'Agriculture accounts for about 70% of water withdrawals.'],
[6,'Which region of the world is least supplied with water?','Southwest Asia and North Africa',['Southeast Asia','Western Europe','South America'],'Countries of the Arabian Peninsula and North Africa rely heavily on seawater desalination.'],
[6,'Which country leads the world in seawater desalination?','Saudi Arabia',['Egypt','Israel','India'],'Saudi Arabia and the UAE are the largest producers of desalinated water.'],
[6,'Which river carries the most water in the world?','The Amazon',['The Congo','The Yangtze','The Mississippi'],'The Amazon carries about 15–20% of the world’s river discharge.'],
[6,'Which country has the greatest hydropower potential and output?','China',['Brazil','Canada','Norway'],'China leads in hydropower generation (the Three Gorges Dam on the Yangtze).'],
[6,'Desertification is most severe in…','the Sahel (Africa)',['Amazonia','Scandinavia','Siberia'],'The Sahel is the belt south of the Sahara suffering from overgrazing and droughts.'],
// ——— 7 ———
[7,'Which country has the largest forest area?','Russia',['Brazil','Canada','United States'],'Russia has about 20% of the world’s forests, followed by Brazil, Canada, the USA and China.'],
[7,'The northern forest belt consists mainly of…','Coniferous forests',['Tropical rainforests','Savannas','Broadleaf evergreen forests'],'The northern belt is coniferous (Russia, Canada, Scandinavia); the southern belt is tropical rainforest (Amazonia, the Congo basin, Southeast Asia).'],
[7,'Which area is called the “lungs of the planet”?','Amazonia',['The Siberian taiga','The Sahara','The Great Plains'],'The Amazon rainforest is the largest tropical rainforest on Earth.'],
[7,'Agroclimatic resources are…','Heat, moisture and light needed by crops',['Soil fertility','Groundwater reserves','Pasture area'],'Heat supply is measured by the sum of active temperatures (above +10 °C).'],
[7,'Which indicator is used to assess the heat available to crops?','The sum of active temperatures',['Mean annual temperature','Temperature range','The moisture coefficient'],'The sum of mean daily temperatures above +10 °C over the growing season.'],
[7,'Which is the most visited country in the world?','France',['United States','Spain','Italy'],'France receives about 100 million foreign tourists a year.'],
[7,'Which country earns the most from international tourism?','United States',['France','Spain','China'],'The USA leads in receipts, France in arrivals.'],
[7,'Which ocean provides the largest catch of fish and seafood?','The Pacific',['The Atlantic','The Indian','The Arctic'],'The Pacific accounts for more than half of the world catch.'],
[7,'Which country leads the world in fish catch and aquaculture?','China',['Japan','Norway','Peru'],'China is the largest fish producer, especially in aquaculture.'],
// ——— 8 ———
[8,'When did the world population reach 8 billion (UN estimate)?','November 2022',['2011','2019','2025'],'7 billion in 2011, 8 billion on 15 November 2022.'],
[8,'Which is the most populous country in the world?','India',['China','United States','Indonesia'],'India overtook China in 2023; the USA is third.'],
[8,'Which type of population reproduction is associated with the “population explosion”?','Type II (traditional) — developing countries',['Type I (modern) — developed countries','The archaic type','The type transitioning to depopulation'],'Type II: high birth rates with rapidly falling death rates → high natural increase.'],
[8,'At what stage of the demographic transition does the “population explosion” occur?','When death rates fall sharply while birth rates stay high',['When birth and death rates are both high','When birth and death rates are both low','When birth rates are below death rates'],'Demographic transition: 1) high births and deaths; 2) deaths fall, births stay high — the explosion; 3) births fall; 4) low births and deaths.'],
[8,'Which country has the highest total fertility rate?','Niger',['India','Egypt','Bangladesh'],'Niger has about 6 children per woman.'],
[8,'Which country has the lowest total fertility rate?','South Korea',['Nigeria','India','United States'],'South Korea has fewer than 1 child per woman (about 0.7–0.75).'],
[8,'What demographic policy did China pursue from 1979 to 2015?','“One family, one child”',['Encouraging higher birth rates','“Two children is the norm”','No demographic policy at all'],'Two children allowed from 2016, three from 2021.'],
[8,'Which country was the first in the world (in 1952) to adopt a national family-planning programme?','India',['China','Japan','Egypt'],'India began a policy of lowering birth rates as early as 1952.'],
[8,'Natural increase of population is…','The difference between the birth rate and the death rate',['The difference between immigration and emigration','The total number of births in a year','Growth due to migration'],'It is measured per mille (‰), i.e. per 1,000 inhabitants.'],
[8,'Which part of the world has the highest rate of natural increase?','Africa',['Asia','Latin America','Europe'],'Africa: about 2.3–2.5% a year.'],
[8,'Depopulation is…','Natural population decline, when deaths exceed births',['Movement from the countryside to cities','Growth in the share of older people','Mass emigration'],'Depopulation is typical of several European countries, Japan and South Korea.'],
[8,'A demographic policy aimed at raising the birth rate is pursued in…','France and Russia',['India and Bangladesh','China (1979–2015)','Nigeria and Niger'],'Maternity capital in Russia, family allowances in France.'],
// ——— 9 ———
[9,'Which language family is the largest in the world?','Indo-European',['Sino-Tibetan','Afroasiatic','Altaic'],'Almost half of humanity speaks Indo-European languages.'],
[9,'Which is the largest people (ethnic group) in the world?','The Chinese (Han)',['Hindustanis','Bengalis','Arabs'],'There are more than 1.2 billion Han Chinese.'],
[9,'Which world religion has the most followers?','Christianity',['Islam','Buddhism','Hinduism'],'About 2.4 billion Christians and about 2 billion Muslims.'],
[9,'Which country has the largest Muslim population?','Indonesia',['Saudi Arabia','Pakistan','Iran'],'Indonesia has more than 230 million Muslims.'],
[9,'Buddhism is the main religion in…','Thailand',['India','Indonesia','the Philippines'],'Buddhist countries: Thailand, Myanmar, Sri Lanka, Cambodia, Laos, Bhutan, Mongolia.'],
[9,'Which national religion is practised in Japan?','Shinto',['Confucianism','Hinduism','Taoism'],'The Japanese follow Shinto and Buddhism.'],
[9,'In which country are most Muslims Shia?','Iran',['Saudi Arabia','Turkey','Egypt'],'Shias predominate in Iran, Iraq, Azerbaijan and Bahrain.'],
[9,'Which is the world’s largest Catholic country?','Brazil',['Italy','Mexico','the Philippines'],'Brazil has the most Catholics.'],
[9,'Which state is almost entirely mono-ethnic?','Japan',['India','Russia','Switzerland'],'Mono-ethnic states: Japan, Iceland, Poland, South Korea and others.'],
[9,'Which state is bi-national?','Belgium',['Germany','Poland','Portugal'],'Belgium — Flemings and Walloons; Canada — English and French Canadians.'],
[9,'Which region of the world has the highest share of children in its age structure?','Tropical Africa',['Western Europe','North America','East Asia'],'In African countries, children under 15 make up more than 40% of the population.'],
[9,'Which country has the highest share of older people (65+)?','Japan',['India','Nigeria','Brazil'],'People aged 65+ make up almost 30% of Japan’s population.'],
[9,'What does the age–sex pyramid of a developing country look like?','A wide base and a narrow top',['A narrow base and a wide top','A rectangle','An “urn” shape'],'A wide base means many children; the “urn” shape is typical of ageing developed countries.'],
[9,'Hinduism is the main religion in…','India and Nepal',['Pakistan and Bangladesh','Sri Lanka and Myanmar','Iran and Afghanistan'],'Pakistan and Bangladesh are Muslim countries; Sri Lanka and Myanmar are Buddhist.'],
// ——— 10 ———
[10,'Which large country has the highest population density?','Bangladesh',['India','China','Japan'],'Bangladesh has more than 1,100 people per km². Among all states, Monaco is densest.'],
[10,'What is the average population density of the Earth’s land?','About 60 people/km²',['About 10 people/km²','About 150 people/km²','About 300 people/km²'],'8 billion people on ~134 million km² of land (excluding Antarctica).'],
[10,'Which state has the lowest population density?','Mongolia',['Kazakhstan','Russia','Canada'],'Mongolia: about 2 people per km².'],
[10,'What share of the world’s population lives in cities?','About 57–58%',['About 30%','About 75%','About 90%'],'Since 2007–2008 there have been more city dwellers than rural residents.'],
[10,'Which part of the world is least urbanized?','Africa',['Europe','Latin America','North America'],'Africa’s urbanization level is about 45%.'],
[10,'What is “false urbanization”?','City growth driven by rural migrants without industrial or infrastructure development',['Growth of suburbs','The spread of urban lifestyles to the countryside','A decline in the number of cities'],'Typical of developing countries: growing slums and unemployment.'],
[10,'Suburbanization is…','The growth of suburban areas around large cities',['A rise in the share of rural population','Out-migration to the countryside','The merging of cities into a megalopolis'],'Rurbanization is the spread of urban lifestyles to rural areas.'],
[10,'Which megalopolis stretches from Boston to Washington?','BosWash',['ChiPitts','SanSan','Tokaido'],'ChiPitts — Chicago–Pittsburgh; SanSan — San Francisco–San Diego; Tokaido — Tokyo–Osaka.'],
[10,'The Tokaido megalopolis is in…','Japan',['China','South Korea','India'],'Tokaido runs from Tokyo to Osaka/Kobe along the Pacific coast of Honshu.'],
[10,'An agglomeration is…','A compact cluster of towns around a large core city, linked by close ties',['Any city with more than 1 million people','A merger of several countries','A workers’ settlement next to a factory'],'Merging agglomerations form a megalopolis.'],
// ——— 11 ———
[11,'What are the main stages in the development of the world economy?','Pre-industrial, industrial, post-industrial',['Agrarian, maritime, space','Colonial, socialist, market','Early, middle, late'],'In the post-industrial stage, services and knowledge play the leading role.'],
[11,'The post-industrial stage is characterized by the predominance in GDP of…','Services',['Agriculture','Extractive industries','Manufacturing'],'In developed countries services account for 70–80% of GDP.'],
[11,'The international geographical division of labour is…','Countries specializing in producing certain goods and services and exchanging them',['Carving up markets among multinationals','Labour migration','Dividing the world into developed and developing countries'],'Industries of international specialization produce mainly for export.'],
[11,'Which location factor becomes more important under the scientific-technological revolution?','Knowledge intensity and a skilled workforce',['Raw materials','Proximity to fuel resources','Cheap unskilled labour'],'The scientific-technological revolution reduces the role of raw-material and fuel factors.'],
[11,'What is the “Green Revolution”?','The transformation of agriculture in developing countries through new crop varieties, irrigation and chemicals',['The switch to organic farming in Europe','Reforestation in the tropics','The growth of renewable energy'],'It covered India, Pakistan, Mexico and the Philippines in the 1960s–70s.'],
[11,'Which country produces more than half of the world’s steel?','China',['India','Japan','United States'],'China: more than 50% of world steel output.'],
[11,'Which country is the largest car producer?','China',['Japan','United States','Germany'],'China makes about a third of the world’s cars and leads in electric vehicles.'],
[11,'Which country has the highest share of nuclear power in its electricity generation?','France',['United States','Japan','Germany'],'Nuclear plants supply about 65–70% of France’s electricity.'],
[11,'Which country is the largest wheat exporter?','Russia',['United States','Canada','Australia'],'Russia has been the top wheat exporter since the late 2010s.'],
[11,'Which country is the largest rice exporter?','India',['China','Thailand','Vietnam'],'China is the largest producer, India the largest exporter, followed by Thailand and Vietnam.'],
[11,'Which country is the world leader in coffee production?','Brazil',['Colombia','Ethiopia','Vietnam'],'Brazil grows about a third of the world’s coffee; Vietnam is second.'],
[11,'Which country is the largest producer of cocoa beans?','Côte d’Ivoire',['Ghana','Brazil','Nigeria'],'Côte d’Ivoire produces about 40% of the world’s cocoa.'],
[11,'Which country is the largest producer of natural rubber?','Thailand',['Brazil','Malaysia','Nigeria'],'Leaders: Thailand, Indonesia, Vietnam.'],
[11,'Which country is the largest producer of palm oil?','Indonesia',['Malaysia','Nigeria','Thailand'],'Indonesia and Malaysia produce more than 80% of palm oil.'],
[11,'Which country is the largest producer of soybeans?','Brazil',['United States','Argentina','China'],'Brazil has overtaken the USA in soybean production.'],
[11,'Which country is the largest producer of tea?','China',['India','Sri Lanka','Kenya'],'China is first, India second; the largest exporters are Kenya, China and Sri Lanka.'],
// ——— 12 ———
[12,'Roughly what share of GDP do services account for in developed countries?','70–80%',['20–30%','40–50%','90–95%'],'Developed countries have a post-industrial economic structure.'],
[12,'Which countries are “first-wave” newly industrialized countries (NICs)?','South Korea, Taiwan, Singapore, Hong Kong',['Malaysia, Thailand, Indonesia, the Philippines','Brazil, Mexico, Argentina','China, India, Vietnam'],'They are known as the “Asian Tigers” (or “Dragons”).'],
[12,'Which countries are “second-wave” NICs?','Malaysia, Thailand, Indonesia',['Singapore, Hong Kong, Taiwan','Japan, Australia, New Zealand','Nigeria, Kenya, Egypt'],'The second wave of industrialization in Southeast Asia came in the 1980s–90s.'],
[12,'Which countries are called the “key countries” of the developing world?','Brazil, Mexico, India',['Chad, Niger, Mali','Singapore, Bahrain, Qatar','Haiti, Nepal, Laos'],'They have large economic potential and a leading role among developing countries.'],
[12,'Where are most of the least developed countries concentrated?','In Tropical Africa',['In Latin America','In Southern Europe','In East Asia'],'Of the ~44 LDCs, more than 30 are in Africa.'],
[12,'A monoculture economy is…','Narrow specialization in one or two products, usually for export',['Growing crops without fertilizer','Combining crop farming and livestock','Subsistence farming'],'Typical of many developing countries (coffee, cocoa, copper, etc.).'],
[12,'Which country is NOT in the G7?','Spain',['Italy','Canada','Japan'],'G7: USA, Japan, Germany, UK, France, Italy, Canada.'],
[12,'What is typical of the territorial structure of developing economies?','A “focal” pattern: activity concentrated in the capital or a port',['An even spread of production','A predominance of highly developed regions','Many technopolises'],'This is a legacy of the colonial era.'],
[12,'What are declining old industrial regions called?','Depressed regions',['Frontier (new development) regions','Technopolises','Free economic zones'],'For example, coal and steel regions (Lorraine, the Ruhr before restructuring).'],
[12,'Which is the world’s largest economy by nominal GDP?','United States',['China','Japan','Germany'],'By GDP at purchasing power parity, China leads.'],
// ——— 13 ———
[13,'Which Western European country has the largest population?','Germany',['France','United Kingdom','Italy'],'Germany has about 83–84 million people.'],
[13,'Which Western European country is the largest by area?','France',['Spain','Germany','Sweden'],'France covers about 550,000 km² (excluding overseas territories).'],
[13,'Which European country gets almost all its electricity from hydropower?','Norway',['France','Netherlands','Denmark'],'Norway: about 90% of electricity from hydropower.'],
[13,'Where is the Kiruna iron ore deposit?','Sweden',['Norway','Finland','Germany'],'Kiruna is one of the largest iron ore deposits in Europe.'],
[13,'The main religion of the Scandinavian countries is…','Protestantism (Lutheranism)',['Catholicism','Orthodox Christianity','Anglicanism'],'Catholicism predominates in Southern Europe, Ireland, Belgium and Austria.'],
[13,'How many official languages does Switzerland have?','Four',['Two','Three','Five'],'German, French, Italian and Romansh.'],
[13,'Which state uses the euro without being an EU member?','Monaco',['Sweden','Denmark','Poland'],'The Vatican, San Marino, Andorra, Montenegro and Kosovo also use the euro.'],
[13,'The main demographic problem of Western Europe is…','An ageing population and low birth rates',['A population explosion','High infant mortality','A male-dominated population'],'In many countries, population growth relies on immigration.'],
[13,'Which microstate lies in the Pyrenees?','Andorra',['Monaco','Liechtenstein','San Marino'],'Andorra lies between France and Spain.'],
[13,'Which Western European country is the most urbanized?','Belgium',['Portugal','Ireland','Greece'],'About 98% of Belgians live in cities.'],
[13,'Which is Europe’s largest seaport?','Rotterdam',['Hamburg','Antwerp','Marseille'],'Rotterdam (Netherlands) is at the mouth of the Rhine.'],
// ——— 14 ———
[14,'What is Germany’s main industry of international specialization?','Car manufacturing',['Oil production','Textiles','Shipbuilding'],'Also chemicals, machine tools and electrical engineering.'],
[14,'Where is Volkswagen headquartered?','Wolfsburg',['Stuttgart','Munich','Cologne'],'Stuttgart — Mercedes-Benz and Porsche; Munich — BMW.'],
[14,'In which city is the chemical giant BASF based?','Ludwigshafen',['Hamburg','Bremen','Dresden'],'Ludwigshafen am Rhein is Europe’s largest chemical complex.'],
[14,'Which is Germany’s largest seaport?','Hamburg',['Bremen','Rostock','Kiel'],'Hamburg lies on the Elbe.'],
[14,'In which year did Germany shut down its last nuclear power plants?','2023',['2011','2018','2030'],'The nuclear phase-out (part of the Energiewende) was completed in April 2023.'],
[14,'How many federal states (Länder) does Germany have?','16',['9','13','26'],'Including the city-states of Berlin, Hamburg and Bremen.'],
[14,'Which is Germany’s main industrial region, formerly based on coal and steel?','The Ruhr',['Saarland','Bavaria','Silesia'],'The Ruhr agglomeration includes Dortmund, Essen, Duisburg and others.'],
[14,'Which city is the centre of France’s aerospace industry (Airbus)?','Toulouse',['Lyon','Lille','Bordeaux'],'Toulouse is Europe’s largest aircraft-building centre.'],
[14,'Lorraine in France is known as an old industrial region of…','Iron and steel making',['Winemaking','Aircraft building','Tourism'],'It was based on local iron ores and is now a depressed region.'],
[14,'Which country is the largest agricultural producer in the EU?','France',['Germany','Spain','Poland'],'France: wheat, sugar beet, wine, dairy products.'],
[14,'Which is France’s largest seaport?','Marseille',['Le Havre','Bordeaux','Brest'],'Marseille is on the Mediterranean; Le Havre at the mouth of the Seine.'],
[14,'Bordeaux, Champagne and Burgundy are French regions famous for…','Winemaking',['Coal mining','Car manufacturing','Nuclear power'],'France is one of the two largest wine producers in the world (with Italy).'],
[14,'The Sophia Antipolis technopolis is located…','In the south of France (Côte d’Azur)',['Near Paris','In Alsace','In Brittany'],'One of the first technology parks in Europe.'],
[14,'The capital region of France is called…','Île-de-France',['Provence','Normandy','Aquitaine'],'Paris and its region produce about a third of France’s GDP.'],
// ——— 15 ———
[15,'Which Central and Eastern European country has the largest population?','Poland',['Romania','Czechia','Hungary'],'Poland has about 37 million people.'],
[15,'What is the backbone of Poland’s power sector?','Coal-fired thermal power plants',['Nuclear power plants','Hydropower plants','Wind farms'],'Poland is the EU’s largest hard-coal producer; its first nuclear plant is still under construction.'],
[15,'Poland’s Legnica–Głogów district is known for mining…','Copper',['Oil','Bauxite','Iron ore'],'Poland is a major producer of copper and silver (KGHM).'],
[15,'Which of these ports belongs to Poland?','Gdańsk',['Klaipėda','Rostock','Constanța'],'Polish ports: Gdańsk, Gdynia, Szczecin.'],
[15,'Poland is the EU’s largest producer of…','Apples',['Olives','Oranges','Rice'],'Poland is one of the world’s leading apple producers.'],
[15,'Which capital is NOT on the Danube?','Prague',['Vienna','Budapest','Belgrade'],'Prague is on the Vltava. Vienna, Bratislava, Budapest and Belgrade are on the Danube.'],
[15,'The Ploiești oil district is in…','Romania',['Hungary','Bulgaria','Poland'],'Ploiești is one of the oldest oil-industry centres in Europe.'],
[15,'Which country is famous for producing rose oil?','Bulgaria',['Serbia','Croatia','Slovakia'],'The Valley of Roses near Kazanlak.'],
[15,'In which country is the Škoda car plant?','Czechia',['Slovakia','Poland','Hungary'],'Mladá Boleslav. Slovakia leads the world in cars made per capita.'],
[15,'Which Central and Eastern European country has a mostly Muslim population?','Albania',['Croatia','Slovenia','Bulgaria'],'Muslims are also the majority in Kosovo and the largest group in Bosnia and Herzegovina.'],
[15,'Which currency is used in Poland?','The złoty',['The euro','The forint','The koruna'],'The forint is Hungary’s currency, the koruna Czechia’s.'],
// ——— 16 ———
[16,'What is the capital of Turkey?','Ankara',['Istanbul','Izmir','Antalya'],'Istanbul is the largest city and economic centre.'],
[16,'Which straits does Turkey control?','The Bosporus and the Dardanelles',['Hormuz and Bab-el-Mandeb','Gibraltar and Messina','Kerch and Otranto'],'The regime of the straits is set by the 1936 Montreux Convention.'],
[16,'Which city is the centre of Turkey’s car industry?','Bursa',['Ankara','Trabzon','Konya'],'Bursa and its surroundings host Renault, Fiat (Tofaş) and other plants.'],
[16,'Turkey is the world leader in producing…','Hazelnuts',['Coffee','Cocoa','Rice'],'Turkey grows about 60–70% of the world’s hazelnuts.'],
[16,'The Atatürk Dam was built on which river?','The Euphrates',['The Tigris','The Kızılırmak','The Nile'],'Part of the Southeastern Anatolia Project (GAP).'],
[16,'Which sectors lead the Turkish economy?','Light industry (textiles), car manufacturing, tourism',['Oil and gas production','Semiconductor manufacturing','Diamond mining'],'Turkey is a major exporter of clothing, textiles, cars and household appliances.'],
[16,'The Suez Canal connects…','The Mediterranean and the Red Sea',['The Black Sea and the Mediterranean','The Red Sea and the Persian Gulf','The Atlantic and the Mediterranean'],'Opened in 1869, owned by Egypt.'],
[16,'Which is the most populous country in the Middle East and North Africa?','Egypt',['Turkey','Iran','Algeria'],'Egypt has more than 110 million people, concentrated in the Nile valley and delta.'],
[16,'Ghawar, the world’s largest oil field, is in…','Saudi Arabia',['Kuwait','Iraq','Iran'],'Ghawar is the largest onshore oil field by reserves.'],
[16,'Which country has the largest phosphate reserves?','Morocco',['Egypt','Tunisia','Jordan'],'Morocco (with Western Sahara) holds about 70% of world reserves.'],
[16,'The Aswan High Dam is on which river?','The Nile',['The Euphrates','The Niger','The Jordan'],'The Aswan hydropower plant is in Egypt.'],
[16,'Which is the only country in the region where Judaism predominates?','Israel',['Lebanon','Jordan','Cyprus'],'The other countries of the region are mostly Muslim.'],
// ——— 17 ———
[17,'Which is Africa’s most populous country?','Nigeria',['Ethiopia','Egypt','DR Congo'],'Nigeria has more than 220 million people.'],
[17,'Which Sub-Saharan country has the most developed economy?','South Africa',['Nigeria','Kenya','Angola'],'South Africa is the only country in the region with a developed manufacturing sector.'],
[17,'The Witwatersrand is the world’s largest mining district for…','Gold (South Africa)',['Copper (Zambia)','Diamonds (Botswana)','Oil (Nigeria)'],'Its centre is Johannesburg.'],
[17,'Which country is the world leader in cobalt mining?','DR Congo',['South Africa','Zambia','Angola'],'DR Congo supplies about 70% of the world’s cobalt.'],
[17,'Which country is Africa’s largest diamond producer (by value)?','Botswana',['South Africa','Namibia','Angola'],'Diamonds are the backbone of Botswana’s economy.'],
[17,'Which country is considered the homeland of coffee?','Ethiopia',['Kenya','Brazil','Yemen'],'The name is linked to the Kaffa province.'],
[17,'Which country is a major exporter of tea and cut flowers?','Kenya',['Chad','Niger','Mali'],'Kenya is one of the world’s largest tea exporters.'],
[17,'Which is the largest oil producer in Tropical Africa?','Nigeria',['Kenya','Tanzania','Ethiopia'],'Oil is produced in the Niger Delta; Nigeria is an OPEC member.'],
[17,'What is typical of agriculture in Tropical Africa?','Subsistence farming alongside export monocultures',['Highly mechanized grain farming','Intensive dairy farming','A predominance of greenhouse farms'],'Plantations (cocoa, coffee, tea) coexist with low-productivity subsistence farming.'],
[17,'The Grand Ethiopian Renaissance Dam is built on…','The Blue Nile',['The White Nile','The Congo','The Zambezi'],'Africa’s largest hydropower plant, inaugurated in 2025.'],
[17,'Which country is the leading producer of cocoa beans in Africa and the world?','Côte d’Ivoire',['Kenya','Angola','Madagascar'],'Ghana is second.'],
[17,'Lake Kariba on the Zambezi lies on the border between…','Zambia and Zimbabwe',['Kenya and Uganda','South Africa and Namibia','Angola and Zambia'],'One of the largest reservoirs in the world.'],
// ——— 18 ———
[18,'Which is the world’s largest landlocked country by area?','Kazakhstan',['Mongolia','Chad','Bolivia'],'Kazakhstan is the 9th largest country in the world.'],
[18,'What is the capital of Kazakhstan?','Astana',['Almaty','Shymkent','Karaganda'],'The capital moved from Almaty to Astana in 1997.'],
[18,'Kashagan is…','An offshore oil field in the Caspian Sea',['A coal basin','A uranium mine','A spaceport'],'Other major Kazakh fields: Tengiz (oil), Karachaganak (gas condensate).'],
[18,'The Ekibastuz basin is known for…','Open-pit coal mining',['Oil production','Copper mining','Cotton growing'],'Ekibastuz coal fuels some of the largest power plants.'],
[18,'Which spaceport is in Kazakhstan?','Baikonur',['Plesetsk','Vostochny','Kourou'],'Baikonur is leased by Russia.'],
[18,'Which Central Asian country has the largest population?','Uzbekistan',['Kazakhstan','Tajikistan','Turkmenistan'],'Uzbekistan has about 37 million people.'],
[18,'Which crop has traditionally been the backbone of Uzbek agriculture?','Cotton',['Rice','Coffee','Tea'],'Irrigating cotton from the Amu Darya and Syr Darya led to the Aral Sea disaster.'],
[18,'Which Central Asian country has the largest natural gas reserves?','Turkmenistan',['Kyrgyzstan','Tajikistan','Kazakhstan'],'The Galkynysh field is one of the largest in the world.'],
[18,'The Nurek and Rogun hydropower plants are on which river?','The Vakhsh (Tajikistan)',['The Naryn (Kyrgyzstan)','The Irtysh (Kazakhstan)','The Amu Darya (Turkmenistan)'],'Tajikistan’s hydropower supplies the aluminium plant in Tursunzoda.'],
[18,'Which environmental disaster is associated with Central Asia?','The shrinking of the Aral Sea',['Pollution of Lake Baikal','Desertification of the Sahel','Melting of Greenland’s glaciers'],'The cause was water withdrawal from the Amu Darya and Syr Darya for irrigation.'],
[18,'Where does Kazakhstan rank in the world for uranium mining?','First',['Second','Fifth','Tenth'],'About 40% of world output.'],
// ——— 19 ———
[19,'Which city is called “India’s Silicon Valley”?','Bangalore (Bengaluru)',['Mumbai','Kolkata','Delhi'],'A centre of IT services and software development.'],
[19,'Where is the centre of India’s “Bollywood” film industry?','Mumbai',['Delhi','Chennai','Bangalore'],'The name combines Bombay (Mumbai’s old name) and Hollywood.'],
[19,'Which Indian regions are famous for tea?','Assam and Darjeeling',['Punjab and Haryana','Gujarat and Rajasthan','Kerala and Goa'],'Punjab is India’s “breadbasket” and the heart of the Green Revolution.'],
[19,'In which product does India rank first in the world?','Milk',['Coffee','Maize','Wool'],'India is the largest milk producer (including buffalo milk).'],
[19,'Which country is the main exporter of jute?','Bangladesh',['Pakistan','Sri Lanka','Nepal'],'Jute is grown in the Ganges–Brahmaputra delta.'],
[19,'Which Indian steel centre was founded by the Tata company?','Jamshedpur',['Bangalore','Mumbai','Hyderabad'],'India’s steel industry is concentrated in the northeast of the Deccan Plateau.'],
[19,'India is called the “pharmacy of the world” because of its…','Pharmaceutical industry (generics)',['Oil refining','Steel industry','Shipbuilding'],'India is the largest exporter of generic drugs.'],
[19,'Which South Asian country is Buddhist?','Sri Lanka',['Pakistan','Bangladesh','Maldives'],'Buddhism is also the state religion of Bhutan.'],
[19,'What is the capital of Pakistan?','Islamabad',['Karachi','Lahore','Peshawar'],'Karachi is Pakistan’s largest city and port.'],
[19,'Which languages are official at the national level in India?','Hindi and English',['Hindi and Urdu','Bengali and English','Sanskrit and Hindi'],'In addition, the constitution recognizes 22 languages.'],
[19,'Which type of climate shapes agriculture in South Asia?','Monsoon',['Mediterranean','Sharply continental','Arctic'],'The summer monsoon brings up to 80% of annual rainfall.'],
[19,'Which South Asian country is most threatened by flooding from rising sea levels?','Maldives',['Nepal','Bhutan','Afghanistan'],'Most of the Maldives lies less than 1.5 m above sea level.'],
// ——— 20 ———
[20,'Which Indonesian island is the most populous (and the most populous island in the world)?','Java',['Sumatra','Borneo (Kalimantan)','Sulawesi'],'More than half of Indonesia’s population lives on Java.'],
[20,'On which island is Indonesia’s new capital, Nusantara, being built?','Borneo (Kalimantan)',['Java','Sumatra','Bali'],'The capital is being moved away from overcrowded Jakarta.'],
[20,'Indonesia is the world leader in mining…','Nickel',['Copper','Uranium','Lithium'],'Indonesia supplies about half of the world’s nickel.'],
[20,'Indonesia is the world’s largest exporter of…','Thermal coal',['Oil','Wheat','Coffee'],'It is also a major exporter of palm oil and liquefied natural gas.'],
[20,'Which religion predominates on the island of Bali?','Hinduism',['Islam','Buddhism','Catholicism'],'Islam predominates in the rest of Indonesia.'],
[20,'Which Southeast Asian country is mostly Catholic?','The Philippines',['Vietnam','Malaysia','Thailand'],'Catholics also predominate in Timor-Leste.'],
[20,'Which Southeast Asian country is landlocked?','Laos',['Cambodia','Myanmar','Vietnam'],'Laos is the only landlocked country in Southeast Asia.'],
[20,'Which Southeast Asian countries are the largest rice exporters?','Thailand and Vietnam',['Singapore and Brunei','Indonesia and the Philippines','Malaysia and Laos'],'Indonesia and the Philippines are major rice importers.'],
[20,'Which Southeast Asian country is one of the world’s biggest financial centres and ports?','Singapore',['Laos','Cambodia','Myanmar'],'Singapore is also a major oil-refining centre.'],
[20,'Which countries does the Mekong flow through?','China, Myanmar, Laos, Thailand, Cambodia, Vietnam',['India, Bangladesh, Myanmar','Indonesia, Malaysia','The Philippines and Vietnam'],'The Mekong is Southeast Asia’s largest river; its delta in Vietnam is the main rice-growing area.'],
[20,'Roughly how many islands does Indonesia have?','More than 17,000',['About 500','About 3,000','About 50,000'],'Indonesia is the world’s largest archipelagic state.'],
[20,'Which Southeast Asian country is the world’s second-largest coffee producer?','Vietnam',['Thailand','The Philippines','Singapore'],'Vietnam specializes in robusta coffee.'],
// ——— 21 ———
[21,'Which is the largest island of Japan?','Honshu',['Hokkaido','Kyushu','Shikoku'],'The four main islands: Honshu, Hokkaido, Kyushu, Shikoku.'],
[21,'What is the main feature of Japan’s resource base?','Scarce mineral resources and dependence on imported raw materials',['The largest oil reserves in Asia','Abundant coal and iron ore','Self-sufficiency in food'],'Japan imports almost all its oil, gas and iron ore.'],
[21,'Where is most of Japan’s population and economic activity concentrated?','On the Pacific coast (the Pacific Belt)',['On Hokkaido','On the Sea of Japan coast','In the inland mountain areas'],'The Tokaido megalopolis: Tokyo — Nagoya — Osaka.'],
[21,'What is Japan’s form of government?','A constitutional monarchy (emperor)',['A presidential republic','An absolute monarchy','A parliamentary republic'],'The emperor is a symbol of the state; power lies with parliament and the government.'],
[21,'The science city of Tsukuba in Japan is…','A technopolis (science city)',['An iron and steel centre','The main fishing port','A textile centre'],'Tsukuba is Japan’s largest research centre.'],
[21,'What is Japan’s main crop?','Rice',['Wheat','Maize','Cotton'],'Japan is also one of the largest consumers of seafood.'],
[21,'Along which line is the Korean Peninsula divided?','Around the 38th parallel',['Along the 49th parallel','Along the 17th parallel','Along the Yalu River'],'The division was fixed in 1948; after the 1950–1953 war came the demilitarized zone.'],
[21,'From which country was Macao returned to China in 1999?','Portugal',['United Kingdom','Spain','Japan'],'Hong Kong was returned by the UK in 1997.'],
[21,'Which East Asian country is landlocked?','Mongolia',['North Korea','South Korea','Japan'],'Mongolia is the second-largest landlocked country after Kazakhstan.'],
[21,'Which country has the highest share of older people and a shrinking population?','Japan',['North Korea','Mongolia','China'],'Japan’s population has been shrinking since the late 2000s.'],
[21,'Which Japanese city is home to Toyota?','Toyota (near Nagoya)',['Sapporo','Hiroshima','Fukuoka'],'The city is named after the company.'],
[21,'Which are the leading branches of Japanese industry?','Cars, electronics, robotics',['Coal and oil production','Light and food industries','Forestry and woodworking'],'Japan leads in industrial robots and is one of the top car producers.'],
// ——— 22 ———
[22,'Which was China’s first special economic zone?','Shenzhen',['Shanghai','Beijing','Tianjin'],'Established in 1980 next to Hong Kong.'],
[22,'How many municipalities directly under the central government does China have?','4',['2','5','7'],'Beijing, Shanghai, Tianjin, Chongqing.'],
[22,'Which of China’s economic zones is the most developed?','The Eastern (coastal) zone',['The Western zone','The Central zone','The Northwestern zone'],'The Eastern zone has the SEZs, ports and most of the industry.'],
[22,'The Three Gorges Dam, the world’s largest hydropower plant, is on which river?','The Yangtze',['The Yellow River','The Amur','The Mekong'],'Capacity: about 22.5 GW.'],
[22,'What is the main grain crop in northern China?','Wheat',['Rice','Tea','Cotton'],'The north grows wheat and maize; the south grows rice and tea.'],
[22,'Which is the world’s largest container port?','Shanghai',['Rotterdam','Singapore','Los Angeles'],'Shanghai is first, Singapore second.'],
[22,'In which year did China launch its policy of “reform and opening up”?','1978',['1949','1966','1991'],'The reforms of Deng Xiaoping.'],
[22,'Daqing is…','China’s largest oil field',['A coal basin','A special economic zone','A tea-growing centre'],'It is in the Northeast (Heilongjiang province).'],
[22,'Which Chinese province is the main coal region?','Shanxi',['Guangdong','Hainan','Yunnan'],'Shanxi and Inner Mongolia lead coal mining.'],
[22,'Which special administrative regions (SARs) does China have?','Hong Kong and Macao',['Tibet and Xinjiang','Shanghai and Beijing','Hainan and Taiwan'],'They operate under the “one country, two systems” principle.'],
[22,'Where does China rank in the world for electricity generation?','First',['Second','Third','Fifth'],'China generates almost a third of the world’s electricity.'],
[22,'Which part of China is the most sparsely populated?','The West (Tibet, Xinjiang)',['The East','The Pearl River Delta','The North China Plain'],'More than 90% of the population lives in the eastern half of the country.'],
// ——— 23 ———
[23,'How many states make up the USA?','50',['48','52','13'],'50 states plus the District of Columbia. Hawaii and Alaska became states in 1959.'],
[23,'What are the four macro-regions of the USA?','Northeast, Midwest, South, West',['North, South, East, West','Atlantic, Prairies, Rockies, Pacific','New England, Texas, California, Alaska'],'The division used by the US Census Bureau.'],
[23,'Which US macro-region was called the “workshop of the nation”?','The Northeast',['The South','The West','The Midwest'],'The Northeast is the historic centre of industry and finance (New York).'],
[23,'The US “Corn Belt” lies in which macro-region?','The Midwest',['The Northeast','The South','The West'],'The Midwest is the “breadbasket” of the USA.'],
[23,'In which state is Silicon Valley?','California',['Texas','Massachusetts','Washington'],'The San Francisco – San Jose area.'],
[23,'Which city is the traditional centre of the US car industry?','Detroit',['Chicago','Pittsburgh','Houston'],'In the state of Michigan.'],
[23,'Which city is an oil-refining centre and home to NASA’s mission control?','Houston',['Dallas','Miami','Denver'],'Houston, Texas.'],
[23,'Which US state is the largest by area?','Alaska',['Texas','California','Montana'],'Alaska was bought from Russia in 1867.'],
[23,'Which US state is the most populous?','California',['Texas','Florida','New York'],'California has about 39 million people.'],
[23,'The Permian Basin, the main US oil-producing area, lies in…','Texas and New Mexico',['Alaska','California','Pennsylvania'],'Shale oil production.'],
[23,'Which US macro-region is part of the “Sun Belt” and has the fastest population growth?','The South',['The Northeast','The Midwest','Alaska'],'The South and West form the “Sun Belt”; the Northeast and Midwest the “Frost (Rust) Belt”.'],
[23,'Where does the USA rank in the world by population?','Third',['First','Second','Fifth'],'After India and China; about 340 million people.'],
[23,'Which group is the largest minority in the USA?','Hispanic and Latino Americans',['African Americans','Asian Americans','Native Americans'],'About 19–20% of the population.'],
[23,'The USA is the world leader in producing…','Maize (corn)',['Rice','Coffee','Natural rubber'],'It is also one of the leaders in soybean and meat production.'],
// ——— 24 ———
[24,'How many independent states are there in Latin America?','33',['20','27','45'],'12 in South America, 8 in Central America and Mexico, 13 in the Caribbean.'],
[24,'What language is spoken in Brazil?','Portuguese',['Spanish','French','English'],'Brazil is a former Portuguese colony.'],
[24,'What is the capital of Brazil?','Brasília',['Rio de Janeiro','São Paulo','Salvador'],'The capital moved there in 1960; São Paulo is the largest city.'],
[24,'Carajás is…','Brazil’s largest iron ore deposit',['An oil field in Venezuela','A copper mine in Chile','A coal basin in Colombia'],'It is in the state of Pará, in Amazonia.'],
[24,'The Itaipu hydropower plant on the Paraná River was built jointly by Brazil and…','Paraguay',['Argentina','Uruguay','Bolivia'],'One of the largest hydropower plants in the world.'],
[24,'Brazil is the world leader in producing…','Coffee, sugar cane, soybeans',['Rice, tea, jute','Wheat, barley, flax','Cocoa, palm oil, rubber'],'Also orange juice and beef.'],
[24,'How does Brazil use sugar cane for energy?','It produces ethanol as a motor fuel',['It burns it in nuclear plants','It exports it to China','It does not use it'],'Brazil is the world’s second-largest producer of bioethanol.'],
[24,'What are people of mixed European and Indigenous descent called?','Mestizos',['Mulattoes','Zambos','Creoles'],'Mulattoes — European and African descent; zambos — Indigenous and African descent.'],
[24,'What are people of mixed European and African descent called?','Mulattoes',['Mestizos','Zambos','Gauchos'],'There are many mulattoes in Brazil and the Caribbean.'],
[24,'When did the Panama Canal come under Panamanian control?','In 1999',['In 1914','In 1977','In 2016'],'The canal opened in 1914 and was controlled by the USA until 1999.'],
[24,'Maquiladoras — assembly plants near the US border — are typical of…','Mexico',['Brazil','Argentina','Cuba'],'They use cheap labour and duty-free imported components.'],
[24,'Which Latin American country specializes in copper (Chuquicamata)?','Chile',['Bolivia','Ecuador','Colombia'],'Chile is the world leader in copper.'],
[24,'Argentina’s Pampas are the main region for…','Grain farming and beef cattle',['Oil production','Coffee growing','Banana production'],'Argentina is a major exporter of wheat, maize, soybeans and beef.'],
[24,'Which Latin American country is French-speaking?','Haiti',['Jamaica','Guyana','Suriname'],'Jamaica and Guyana are English-speaking; Suriname is Dutch-speaking.'],
[24,'How many states does Brazil have?','26 plus the Federal District',['50','16','32'],'Brazil is a federal republic.'],
[24,'Which Brazilian company is one of the world’s largest aircraft makers?','Embraer',['Petrobras','Vale','Gerdau'],'Petrobras — oil; Vale — mining (iron ore).'],
// ——— 25 ———
[25,'What is the capital of Australia?','Canberra',['Sydney','Melbourne','Perth'],'Sydney is the largest city.'],
[25,'The Pilbara is Australia’s main region for mining…','Iron ore',['Coal','Oil','Opals'],'In Western Australia.'],
[25,'Where does most of Australia’s population live?','On the southeastern and eastern coast',['In the central desert','On the northern coast','On Tasmania'],'Sydney, Melbourne, Brisbane, Canberra.'],
[25,'In which livestock product has Australia historically been the world leader?','Wool (Merino sheep)',['Pork','Milk','Poultry'],'Australia is the largest exporter of wool.'],
[25,'What are Australia’s form of government and territorial structure?','A constitutional monarchy and a federation',['A presidential republic and a unitary state','An absolute monarchy and a federation','A parliamentary republic and a confederation'],'The head of state is the British monarch; 6 states and territories.'],
[25,'Fiji belongs to…','Melanesia',['Polynesia','Micronesia','Australasia'],'Melanesia: New Guinea, the Solomon Islands, Vanuatu, New Caledonia, Fiji.'],
[25,'Samoa, Tonga and Tuvalu belong to…','Polynesia',['Melanesia','Micronesia','Indonesia'],'Polynesia (“many islands”): the triangle of Hawaii — New Zealand — Easter Island.'],
[25,'Nauru, Palau and the Marshall Islands belong to…','Micronesia',['Melanesia','Polynesia','Australia'],'Micronesia means “small islands”.'],
[25,'Nauru’s economy was historically based on mining…','Phosphates',['Gold','Oil','Nickel'],'The phosphate deposits are almost exhausted.'],
[25,'New Zealand is the world’s largest exporter of…','Dairy products',['Iron ore','Coffee','Oil'],'Also lamb and wool.'],
[25,'Which country leads the world in lithium mining?','Australia',['Chile','China','Argentina'],'Australia extracts lithium from spodumene ores.'],
[25,'Which country has the greatest linguistic diversity (more than 800 languages)?','Papua New Guinea',['Australia','Fiji','New Zealand'],'About 840 languages.'],
[25,'Which basin supplies water to the pastures of inland Australia?','The Great Artesian Basin',['The Murray–Darling Basin','The Great Barrier Basin','The Western Australian Basin'],'One of the largest artesian basins in the world.'],
[25,'Which Oceanian state is threatened by flooding from rising sea levels?','Tuvalu',['Papua New Guinea','New Zealand','Fiji'],'Tuvalu’s atolls rise only 4–5 m above sea level.'],
[25,'What share of Australia’s population are Indigenous peoples (Aboriginal and Torres Strait Islanders)?','About 3–4%',['About 25%','About 50%','Less than 0.1%'],'Most Australians are of European descent; the share of Asian immigrants is growing.'],
];
