// English translations of the map data. Keys match the Russian data files.

// Country names by ISO 3166-1 numeric code (same keys as COUNTRIES)
window.COUNTRY_EN = {
  '004':'Afghanistan', '008':'Albania', '012':'Algeria', '020':'Andorra', '024':'Angola', '028':'Antigua and Barbuda',
  '031':'Azerbaijan', '032':'Argentina', '036':'Australia', '040':'Austria', '044':'The Bahamas', '048':'Bahrain',
  '050':'Bangladesh', '051':'Armenia', '052':'Barbados', '056':'Belgium', '064':'Bhutan', '068':'Bolivia',
  '070':'Bosnia and Herzegovina', '072':'Botswana', '076':'Brazil', '084':'Belize', '090':'Solomon Islands', '096':'Brunei',
  '100':'Bulgaria', '104':'Myanmar', '108':'Burundi', '112':'Belarus', '116':'Cambodia', '120':'Cameroon',
  '124':'Canada', '132':'Cabo Verde', '140':'Central African Republic', '144':'Sri Lanka', '148':'Chad', '152':'Chile',
  '156':'China', '158':'Taiwan', '170':'Colombia', '174':'Comoros', '178':'Republic of the Congo', '180':'DR Congo',
  '188':'Costa Rica', '191':'Croatia', '192':'Cuba', '196':'Cyprus', '203':'Czechia', '204':'Benin',
  '208':'Denmark', '212':'Dominica', '214':'Dominican Republic', '218':'Ecuador', '222':'El Salvador', '226':'Equatorial Guinea',
  '231':'Ethiopia', '232':'Eritrea', '233':'Estonia', '242':'Fiji', '246':'Finland', '250':'France',
  '262':'Djibouti', '266':'Gabon', '268':'Georgia', '270':'The Gambia', '275':'Palestine', '276':'Germany',
  '288':'Ghana', '296':'Kiribati', '300':'Greece', '308':'Grenada', '320':'Guatemala', '324':'Guinea',
  '328':'Guyana', '332':'Haiti', '336':'Vatican City', '340':'Honduras', '344':'Hong Kong', '348':'Hungary',
  '352':'Iceland', '356':'India', '360':'Indonesia', '364':'Iran', '368':'Iraq', '372':'Ireland',
  '376':'Israel', '380':'Italy', '384':'Côte d’Ivoire', '388':'Jamaica', '392':'Japan', '398':'Kazakhstan',
  '400':'Jordan', '404':'Kenya', '408':'North Korea', '410':'South Korea', '414':'Kuwait', '417':'Kyrgyzstan',
  '418':'Laos', '422':'Lebanon', '426':'Lesotho', '428':'Latvia', '430':'Liberia', '434':'Libya',
  '438':'Liechtenstein', '440':'Lithuania', '442':'Luxembourg', '446':'Macao', '450':'Madagascar', '454':'Malawi',
  '458':'Malaysia', '462':'Maldives', '466':'Mali', '470':'Malta', '478':'Mauritania', '480':'Mauritius',
  '484':'Mexico', '492':'Monaco', '496':'Mongolia', '498':'Moldova', '499':'Montenegro', '504':'Morocco',
  '508':'Mozambique', '512':'Oman', '516':'Namibia', '520':'Nauru', '524':'Nepal', '528':'Netherlands',
  '548':'Vanuatu', '554':'New Zealand', '558':'Nicaragua', '562':'Niger', '566':'Nigeria', '578':'Norway',
  '583':'Micronesia', '584':'Marshall Islands', '585':'Palau', '586':'Pakistan', '591':'Panama', '598':'Papua New Guinea',
  '600':'Paraguay', '604':'Peru', '608':'Philippines', '616':'Poland', '620':'Portugal', '624':'Guinea-Bissau',
  '626':'Timor-Leste', '634':'Qatar', '642':'Romania', '643':'Russia', '646':'Rwanda', '659':'Saint Kitts and Nevis',
  '662':'Saint Lucia', '670':'Saint Vincent and the Grenadines', '674':'San Marino', '678':'São Tomé and Príncipe', '682':'Saudi Arabia', '686':'Senegal',
  '688':'Serbia', '690':'Seychelles', '694':'Sierra Leone', '702':'Singapore', '703':'Slovakia', '704':'Vietnam',
  '705':'Slovenia', '706':'Somalia', '710':'South Africa', '716':'Zimbabwe', '724':'Spain', '728':'South Sudan',
  '729':'Sudan', '732':'Western Sahara', '740':'Suriname', '748':'Eswatini', '752':'Sweden', '756':'Switzerland',
  '760':'Syria', '762':'Tajikistan', '764':'Thailand', '768':'Togo', '776':'Tonga', '780':'Trinidad and Tobago',
  '784':'United Arab Emirates', '788':'Tunisia', '792':'Turkey', '795':'Turkmenistan', '798':'Tuvalu', '800':'Uganda',
  '804':'Ukraine', '807':'North Macedonia', '818':'Egypt', '826':'United Kingdom', '834':'Tanzania', '840':'United States',
  '854':'Burkina Faso', '858':'Uruguay', '860':'Uzbekistan', '862':'Venezuela', '882':'Samoa', '887':'Yemen',
  '894':'Zambia', 'XK':'Kosovo'
};

window.CONTINENTS_EN = { EU:'Europe', AS:'Asia', AF:'Africa', NA:'North and Central America', SA:'South America', OC:'Australia and Oceania' };

// International organizations (keys = ORGS[].id)
window.ORGS_EN = {
  au: { short:'AU', name:'African Union',
    info:'Founded in 2002 as the successor to the OAU (1963). Headquarters: Addis Ababa. 55 members, including the Sahrawi Arab Democratic Republic (Western Sahara). Several members have been suspended after military coups.' },
  asean: { short:'ASEAN', name:'Association of Southeast Asian Nations',
    info:'Founded in 1967. Secretariat: Jakarta. Timor-Leste became the 11th member in October 2025.' },
  apec: { short:'APEC', name:'Asia-Pacific Economic Cooperation',
    info:'Founded in 1989. Secretariat: Singapore. 21 “member economies”: Hong Kong and Taiwan (as “Chinese Taipei”) take part as separate economies.' },
  brics: { short:'BRICS', name:'Brazil, Russia, India, China, South Africa and others',
    info:'BRIC formed in 2006; South Africa joined in 2011. Egypt, Ethiopia, Iran and the UAE joined in 2024, Indonesia in January 2025. Saudi Arabia was invited but has not formally completed accession.' },
  rcep: { short:'RCEP', name:'Regional Comprehensive Economic Partnership',
    info:'The world’s largest free-trade area. Signed in 2020, in force since 2022. The 10 ASEAN states plus China, Japan, South Korea, Australia and New Zealand.' },
  eaeu: { short:'EAEU', name:'Eurasian Economic Union',
    info:'In operation since 1 January 2015. Executive body: the Eurasian Economic Commission (Moscow). 5 members.' },
  eu: { short:'EU', name:'European Union',
    info:'Maastricht Treaty, 1992 (built on the EEC, 1957). Institutions in Brussels, Strasbourg and Luxembourg. 27 members; the United Kingdom left in 2020. Latest member: Croatia (2013).' },
  las: { short:'Arab League', name:'League of Arab States',
    info:'Founded in 1945. Headquarters: Cairo. 22 members, including Palestine.' },
  aladi: { short:'ALADI', name:'Latin American Integration Association',
    info:'Founded in 1980 as the successor to LAFTA (1960). Headquarters: Montevideo. 13 members.' },
  mercosur: { short:'MERCOSUR', name:'Southern Common Market',
    info:'Founded in 1991 (Treaty of Asunción). Secretariat: Montevideo. Bolivia has been a full member since 2024. Venezuela has been suspended since 2016.' },
  nato: { short:'NATO', name:'North Atlantic Treaty Organization',
    info:'Founded in 1949. Headquarters: Brussels. 32 members; the most recent are Finland (2023) and Sweden (2024).' },
  oas: { short:'OAS', name:'Organization of American States',
    info:'Founded in 1948. Headquarters: Washington, D.C. Brings together all 35 independent states of the Americas. Nicaragua left in 2023; Cuba is formally a member but has not taken part since 1962; Venezuela announced its withdrawal in 2017.' },
  opec: { short:'OPEC', name:'Organization of the Petroleum Exporting Countries',
    info:'Founded in 1960 (Baghdad). Headquarters: Vienna. 12 members. Angola left in 2024, Qatar in 2019, Ecuador in 2020. Russia takes part in OPEC+ but is not an OPEC member.' },
  csto: { short:'CSTO', name:'Collective Security Treaty Organization',
    info:'Treaty signed in 1992, organization since 2002. Secretariat: Moscow. Armenia “froze” its participation in 2024.' },
  saarc: { short:'SAARC', name:'South Asian Association for Regional Cooperation',
    info:'Founded in 1985. Secretariat: Kathmandu. 8 members (Afghanistan since 2007).' },
  cis: { short:'CIS', name:'Commonwealth of Independent States',
    info:'Founded in 1991. Executive Committee: Minsk. Turkmenistan has been an associate member since 2005. Georgia left in 2009; Ukraine ended its participation in 2018. Moldova is withdrawing from CIS agreements.' },
  gcc: { short:'GCC', name:'Gulf Cooperation Council',
    info:'Founded in 1981. Headquarters: Riyadh. The 6 monarchies of the Arabian Peninsula.' },
  sco: { short:'SCO', name:'Shanghai Cooperation Organisation',
    info:'Founded in 2001. Secretariat: Beijing. India and Pakistan joined in 2017, Iran in 2023, Belarus in 2024.' },
  efta: { short:'EFTA', name:'European Free Trade Association',
    info:'Founded in 1960. Headquarters: Geneva. 4 members.' },
  usmca: { short:'USMCA', name:'United States–Mexico–Canada Agreement (formerly NAFTA)',
    info:'In force since 2020, replacing NAFTA (1994).' },
  g7: { short:'G7', name:'Group of Seven',
    info:'An informal club of leading developed economies (since 1975–1976). Russia took part as the G8 in 1997–2014.' },
  g20: { short:'G20', name:'Group of Twenty',
    info:'19 countries + the European Union + the African Union (since 2023).' },
  oecd: { short:'OECD', name:'Organisation for Economic Co-operation and Development',
    info:'Founded in 1961. Headquarters: Paris. 38 members, mostly developed countries.' },
  guam: { short:'GUAM', name:'Organization for Democracy and Economic Development',
    info:'Founded in 1997; the name comes from the members’ initials. Secretariat: Kyiv.' },
  ecowas: { short:'ECOWAS', name:'Economic Community of West African States',
    info:'Founded in 1975. Headquarters: Abuja. Mali, Burkina Faso and Niger left in January 2025 and formed the Alliance of Sahel States.' },
  caricom: { short:'CARICOM', name:'Caribbean Community',
    info:'Founded in 1973. Secretariat: Georgetown (Guyana). 15 members: 14 states plus the British territory of Montserrat.' },
  can: { short:'Andean Community', name:'Andean Community',
    info:'Founded in 1969 (Andean Pact). Secretariat: Lima. Chile left in 1976, Venezuela in 2006.' },
  commonwealth: { short:'Commonwealth', name:'Commonwealth of Nations',
    info:'56 states, mostly former British territories. Gabon and Togo joined in 2022. In 15 of them the British monarch is head of state.' },
};

// Regions (keys = REGIONS[].id)
window.REGIONS_EN = {
  we:'Western Europe', cee:'Central and Eastern Europe', mena:'Middle East and North Africa', ssa:'Sub-Saharan Africa',
  ca:'Central Asia', sa:'South Asia', sea:'Southeast Asia', ea:'East Asia', la:'Latin America', oc:'Australia and Oceania',
};

// Forms of government
window.GOV_LABELS_EN = { rep:'Republic', const:'Constitutional monarchy', abs:'Absolute monarchy', theo:'Theocratic monarchy' };
const REALM_EN = 'the British monarch (represented by a governor-general); a Commonwealth realm';
// Head-of-state notes, keyed by the Russian country name (as in MONARCHIES)
window.MONARCHY_EN = {
  'Саудовская Аравия':'a king; an absolute monarchy with a theocratic character (law based on Sharia)',
  'Оман':'a sultan', 'Бруней':'a sultan', 'Катар':'an emir',
  'ОАЭ':'a federation of 7 emirates (absolute monarchies); the president is chosen from among the emirs',
  'Эсватини':'a king',
  'Ватикан':'the Pope, head of the Roman Catholic Church',
  'Великобритания':'a king', 'Норвегия':'a king', 'Швеция':'a king', 'Дания':'a king', 'Нидерланды':'a king', 'Бельгия':'a king',
  'Испания':'a king', 'Люксембург':'a grand duke', 'Лихтенштейн':'a prince', 'Монако':'a prince',
  'Андорра':'two co-princes: the President of France and the Bishop of Urgell (Spain)',
  'Япония':'an emperor', 'Таиланд':'a king', 'Камбоджа':'a king',
  'Малайзия':'a paramount ruler (king) elected for 5 years from among the state sultans',
  'Бутан':'a king; a constitutional monarchy since 2008', 'Иордания':'a king',
  'Кувейт':'an emir; parliament was dissolved in 2024', 'Бахрейн':'a king',
  'Марокко':'a king', 'Лесото':'a king', 'Тонга':'a king',
  'Канада':REALM_EN, 'Австралия':REALM_EN, 'Новая Зеландия':REALM_EN, 'Папуа — Новая Гвинея':REALM_EN,
  'Соломоновы Острова':REALM_EN, 'Тувалу':REALM_EN, 'Ямайка':REALM_EN, 'Багамские Острова':REALM_EN, 'Белиз':REALM_EN,
  'Антигуа и Барбуда':REALM_EN, 'Сент-Китс и Невис':REALM_EN, 'Сент-Люсия':REALM_EN,
  'Сент-Винсент и Гренадины':REALM_EN, 'Гренада':REALM_EN,
};
window.REPUBLIC_NOTES_EN = {
  'Барбадос':'a republic since 2021 (previously a Commonwealth realm)',
  'Маврикий':'a republic since 1992',
  'Тринидад и Тобаго':'a republic since 1976',
  'Самоа':'a parliamentary republic; the head of state is elected by parliament',
  'Швейцария':'a federal republic (officially a Confederation)',
  'США':'a presidential republic', 'Бразилия':'a presidential republic', 'Мексика':'a presidential republic',
  'Германия':'a parliamentary republic', 'Италия':'a parliamentary republic', 'Индия':'a parliamentary republic',
  'Франция':'a semi-presidential republic', 'Россия':'a semi-presidential republic',
  'Иран':'an Islamic (theocratic) republic',
};
window.FEDERATIONS_EN = {
  'Россия':'federal subjects: republics, krais, oblasts, federal cities, autonomous okrugs (89 under the Russian Constitution)',
  'США':'50 states and the District of Columbia', 'Канада':'10 provinces and 3 territories', 'Мексика':'31 states and the capital',
  'Бразилия':'26 states and the Federal District', 'Аргентина':'23 provinces and the capital district',
  'Венесуэла':'23 states and the Capital District', 'Германия':'16 federal states (Länder)', 'Австрия':'9 federal states (Länder)',
  'Швейцария':'26 cantons', 'Бельгия':'3 regions and 3 language communities',
  'Босния и Герцеговина':'the Federation of BiH, Republika Srpska and the Brčko District',
  'Индия':'28 states and 8 union territories', 'Пакистан':'4 provinces and territories', 'Непал':'7 provinces (a federation since 2015)',
  'Малайзия':'13 states and 3 federal territories', 'Мьянма':'regions and ethnic states',
  'Ирак':'governorates and the autonomous Kurdistan Region', 'ОАЭ':'7 emirates', 'Австралия':'6 states and territories',
  'Нигерия':'36 states and the Federal Capital Territory', 'Эфиопия':'regions drawn along ethnic lines', 'Сомали':'federal member states',
  'Южный Судан':'states', 'Судан':'states', 'Коморы':'3 islands (Union of the Comoros)',
  'Сент-Китс и Невис':'2 islands: Saint Kitts and Nevis', 'Микронезия':'4 states',
};
window.UNITARY_NOTES_EN = {
  'Франция':'unitary state: regions and departments',
  'Великобритания':'unitary state with devolved nations (Scotland, Wales, Northern Ireland)',
  'Испания':'unitary state with autonomous communities', 'Италия':'unitary state: 20 regions',
  'Китай':'unitary state: provinces, autonomous regions, municipalities and the Hong Kong and Macao SARs',
  'Япония':'unitary state: 47 prefectures', 'Казахстан':'unitary state: regions and cities of national significance',
  'Польша':'unitary state: 16 voivodeships', 'Индонезия':'unitary state: provinces',
};

// Straits, in the same order as STRAITS: [name, connects, separates]
window.STRAITS_EN = [
  ['Strait of Gibraltar', 'the Mediterranean Sea and the Atlantic Ocean', 'Europe (Spain) from Africa (Morocco)'],
  ['Bosporus', 'the Black Sea and the Sea of Marmara', 'the European and Asian parts of Turkey'],
  ['Dardanelles', 'the Sea of Marmara and the Aegean Sea', 'the Gallipoli Peninsula (Europe) from Asia Minor'],
  ['Kerch Strait', 'the Sea of Azov and the Black Sea', 'the Kerch (Crimean) and Taman peninsulas'],
  ['Bab-el-Mandeb', 'the Red Sea and the Gulf of Aden (Indian Ocean)', 'the Arabian Peninsula (Yemen) from Africa (Djibouti)'],
  ['Strait of Hormuz', 'the Persian Gulf and the Gulf of Oman', 'Iran from the Arabian Peninsula (Oman)'],
  ['Strait of Malacca', 'the Andaman Sea and the South China Sea (Indian and Pacific oceans)', 'the Malay Peninsula from Sumatra'],
  ['Singapore Strait', 'the Strait of Malacca and the South China Sea', 'Singapore Island from the Riau Islands (Indonesia)'],
  ['Sunda Strait', 'the Java Sea and the Indian Ocean', 'the islands of Sumatra and Java'],
  ['Lombok Strait', 'the Bali Sea and the Indian Ocean', 'the islands of Bali and Lombok'],
  ['Makassar Strait', 'the Celebes Sea and the Java Sea', 'the islands of Borneo (Kalimantan) and Sulawesi'],
  ['Torres Strait', 'the Arafura Sea and the Coral Sea', 'New Guinea from Australia (Cape York Peninsula)'],
  ['Bass Strait', 'the Tasman Sea and the Indian Ocean', 'mainland Australia from Tasmania'],
  ['Cook Strait', 'the Tasman Sea and the Pacific Ocean', 'the North and South Islands of New Zealand'],
  ['Korea (Tsushima) Strait', 'the Sea of Japan and the East China Sea', 'the Korean Peninsula from the Japanese islands (Kyushu)'],
  ['Tsugaru Strait', 'the Sea of Japan and the Pacific Ocean', 'the islands of Honshu and Hokkaido'],
  ['La Pérouse (Sōya) Strait', 'the Sea of Japan and the Sea of Okhotsk', 'the islands of Sakhalin and Hokkaido'],
  ['Strait of Tartary', 'the Sea of Japan and the Sea of Okhotsk (via the Amur Liman)', 'Sakhalin Island from mainland Eurasia'],
  ['Bering Strait', 'the Arctic Ocean (Chukchi Sea) and the Pacific Ocean (Bering Sea)', 'Eurasia (Chukotka) from North America (Alaska)'],
  ['Taiwan Strait', 'the South China Sea and the East China Sea', 'Taiwan from mainland China'],
  ['Hainan (Qiongzhou) Strait', 'the South China Sea and the Gulf of Tonkin', 'Hainan Island from the Leizhou Peninsula'],
  ['Palk Strait', 'the Bay of Bengal and the Gulf of Mannar', 'India (Hindustan) from Sri Lanka'],
  ['Mozambique Channel', 'parts of the Indian Ocean (the world’s longest strait, ~1,760 km)', 'Africa from Madagascar'],
  ['Strait of Magellan', 'the Atlantic and Pacific oceans', 'mainland South America from Tierra del Fuego'],
  ['Drake Passage', 'the Atlantic and Pacific oceans (the world’s widest and deepest strait)', 'South America (Tierra del Fuego) from Antarctica'],
  ['Straits of Florida', 'the Gulf of Mexico and the Atlantic Ocean', 'the Florida Peninsula from Cuba and the Bahamas'],
  ['Yucatán Channel', 'the Gulf of Mexico and the Caribbean Sea', 'the Yucatán Peninsula from Cuba'],
  ['Windward Passage', 'the Atlantic Ocean and the Caribbean Sea', 'the islands of Cuba and Hispaniola (Haiti)'],
  ['Davis Strait', 'Baffin Bay and the Labrador Sea', 'Greenland from Baffin Island'],
  ['Hudson Strait', 'Hudson Bay and the Labrador Sea', 'Baffin Island from the Labrador Peninsula'],
  ['Denmark Strait', 'the Greenland Sea and the Atlantic Ocean (Irminger Sea)', 'Greenland from Iceland'],
  ['Cabot Strait', 'the Gulf of Saint Lawrence and the Atlantic Ocean', 'Newfoundland from Cape Breton Island'],
  ['English Channel', 'the Atlantic Ocean and (via the Strait of Dover) the North Sea', 'Great Britain from France'],
  ['Strait of Dover', 'the English Channel and the North Sea', 'Great Britain from France (32 km at its narrowest)'],
  ['North Channel', 'the Irish Sea and the Atlantic Ocean', 'Ireland (Northern Ireland) from Scotland'],
  ['St George’s Channel', 'the Irish Sea and the Celtic Sea', 'Ireland from Wales (UK)'],
  ['Skagerrak', 'the North Sea and the Kattegat', 'Norway from Denmark (Jutland Peninsula)'],
  ['Kattegat', 'the Skagerrak and the Baltic Sea (via the Danish straits)', 'Sweden from Denmark (Jutland Peninsula)'],
  ['Øresund (The Sound)', 'the Kattegat and the Baltic Sea', 'Sweden from the island of Zealand (Denmark)'],
  ['Strait of Otranto', 'the Adriatic and Ionian seas', 'Italy from Albania'],
  ['Strait of Messina', 'the Tyrrhenian and Ionian seas', 'Sicily from the Italian (Apennine) Peninsula'],
  ['Strait of Bonifacio', 'the Tyrrhenian Sea and the Mediterranean (Sardinian) Sea', 'the islands of Corsica and Sardinia'],
  ['Strait of Sicily (Tunisian Strait)', 'the western and eastern Mediterranean', 'Sicily from Africa (Tunisia)'],
  ['Kara Gates', 'the Barents and Kara seas', 'Novaya Zemlya from Vaygach Island'],
  ['Vilkitsky Strait', 'the Kara Sea and the Laptev Sea', 'the Taymyr Peninsula from the Severnaya Zemlya archipelago'],
];

window.TOPICS_EN = {
  1:'The political map: its stages and changes after World War II',
  2:'State territory, borders, territorial waters, EEZ, continental shelf',
  3:'Forms of government and territorial organization. International organizations',
  4:'Natural conditions and resources; resource endowment',
  5:'Mineral resources; major oil, gas and coal basins',
  6:'Land and water resources',
  7:'Biological, agroclimatic and recreational resources',
  8:'Population size and reproduction; demographic policy',
  9:'Age, ethnic and religious composition of the population',
  10:'Settlement, population density, urbanization',
  11:'The world economy, the international division of labour, industry location under the scientific-technological revolution',
  12:'Economic structure of developed and developing countries',
  13:'Western Europe',
  14:'The economies of Germany and France',
  15:'Central and Eastern Europe. Poland',
  16:'The Middle East and North Africa. Turkey',
  17:'Sub-Saharan Africa',
  18:'Central Asia. Kazakhstan',
  19:'South Asia. India',
  20:'Southeast Asia. Indonesia',
  21:'East Asia. Japan',
  22:'The economy of China',
  23:'Geography of the USA',
  24:'Latin America. Brazil',
  25:'Australia and Oceania',
};
